export const API_BASE_URL = '/api'

export const API_ENDPOINTS = {
  LOGIN: '/api/auth/login',
  REGISTER: '/api/auth/register',
  ME: '/api/auth/me',
  PATIENTS: '/api/patients',
  PATIENT_DETAIL: (id: number) => `/api/patients/${id}`,
  CREATE_SESSION: '/api/diagnosis/sessions',
  GET_SESSION: (id: number) => `/api/diagnosis/sessions/${id}`,
  PATIENT_SESSIONS: (patientId: number) => `/api/diagnosis/patients/${patientId}/sessions`,
  SAVE_INSPECTION: (id: number) => `/api/diagnosis/sessions/${id}/inspection`,
  SAVE_AUSCULTATION: (id: number) => `/api/diagnosis/sessions/${id}/auscultation`,
  SAVE_INQUIRY: (id: number) => `/api/diagnosis/sessions/${id}/inquiry`,
  SAVE_PALPATION: (id: number) => `/api/diagnosis/sessions/${id}/palpation`,
  COMPLETE_SESSION: (id: number) => `/api/diagnosis/sessions/${id}/complete`,
  AI_DIAGNOSE: '/api/ai-diagnosis/diagnose',
  AI_RESULT: (sessionId: number) => `/api/ai-diagnosis/sessions/${sessionId}`,
  AI_REVIEW: (resultId: number) => `/api/ai-diagnosis/review/${resultId}`,
  PRESCRIPTIONS: '/api/prescriptions',
  PRESCRIPTION_BY_SESSION: (sessionId: number) => `/api/prescriptions/sessions/${sessionId}`,
  TREATMENT_PLAN: '/api/prescriptions/treatment-plan',
  DEVICES: '/api/devices',
  DEVICE_REGISTER: '/api/devices/register',
  DEVICE_STATUS: (id: number) => `/api/devices/${id}/status`,
  HEALTH: '/api/health',
  STATS_DASHBOARD: '/api/stats/dashboard',
  STATS_MONTHLY_TREND: '/api/stats/monthly-trend',
  STATS_TOP_HERBS: '/api/stats/top-herbs',
  STATS_PATTERNS: '/api/stats/patterns',
  STATS_DRUGS: '/api/stats/drugs',

  // 进货管理
  PURCHASES: '/api/pharmacy/purchases',
  PURCHASE_DETAIL: (id: number) => `/api/pharmacy/purchases/${id}`,
  DRUGS: '/api/pharmacy/drugs',
  PRICES: '/api/pharmacy/prices',
} as const
