"""init

Revision ID: 7623556f01e1
Revises: 
Create Date: 2026-06-26 12:29:41.910219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7623556f01e1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_name', sa.String(length=64), nullable=False),
    sa.Column('patient_phone', sa.String(length=20), nullable=True),
    sa.Column('doctor', sa.String(length=64), nullable=True),
    sa.Column('department', sa.String(length=64), nullable=True),
    sa.Column('appointment_date', sa.Date(), nullable=False),
    sa.Column('time_slot', sa.String(length=20), nullable=True),
    sa.Column('visit_type', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appointments_id'), 'appointments', ['id'], unique=False)
    op.create_table('drug_prices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment='药材名称'),
    sa.Column('spec', sa.String(length=100), nullable=False, comment='规格'),
    sa.Column('price', sa.Float(), nullable=True, comment='价格（元）'),
    sa.Column('origin', sa.String(length=100), nullable=True, comment='产地'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drug_prices_id'), 'drug_prices', ['id'], unique=False)
    op.create_index(op.f('ix_drug_prices_name'), 'drug_prices', ['name'], unique=False)
    op.create_table('followups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('patient_name', sa.String(length=64), nullable=True),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('followup_date', sa.Date(), nullable=False),
    sa.Column('followup_type', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('satisfaction', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_followups_id'), 'followups', ['id'], unique=False)
    op.create_index(op.f('ix_followups_patient_id'), 'followups', ['patient_id'], unique=False)
    op.create_index(op.f('ix_followups_session_id'), 'followups', ['session_id'], unique=False)
    op.create_table('nursing_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('nurse_name', sa.String(length=64), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nursing_records_id'), 'nursing_records', ['id'], unique=False)
    op.create_index(op.f('ix_nursing_records_patient_id'), 'nursing_records', ['patient_id'], unique=False)
    op.create_table('schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doctor_name', sa.String(length=64), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('time_slot', sa.String(length=20), nullable=True),
    sa.Column('max_patients', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schedules_date'), 'schedules', ['date'], unique=False)
    op.create_index(op.f('ix_schedules_doctor_name'), 'schedules', ['doctor_name'], unique=False)
    op.create_index(op.f('ix_schedules_id'), 'schedules', ['id'], unique=False)
    op.add_column('ai_diagnosis_results', sa.Column('health_advice', sa.JSON(), nullable=True))
    op.add_column('drugs', sa.Column('category_id', sa.Integer(), nullable=True))
    op.add_column('drugs', sa.Column('category_name', sa.String(length=50), nullable=True))
    op.add_column('drugs', sa.Column('property_taste', sa.String(length=100), nullable=True))
    op.add_column('drugs', sa.Column('meridian', sa.String(length=100), nullable=True))
    op.add_column('drugs', sa.Column('effect', sa.Text(), nullable=True))
    op.add_column('drugs', sa.Column('dosage', sa.String(length=50), nullable=True))
    op.add_column('drugs', sa.Column('contraindication', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'drugs', 'drug_categories', ['category_id'], ['id'])
    op.drop_column('drugs', 'category')
    op.alter_column('patients', 'bmi',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('patients', 'bmi',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.add_column('drugs', sa.Column('category', sa.VARCHAR(length=50), nullable=True))
    op.drop_constraint(None, 'drugs', type_='foreignkey')
    op.drop_column('drugs', 'contraindication')
    op.drop_column('drugs', 'dosage')
    op.drop_column('drugs', 'effect')
    op.drop_column('drugs', 'meridian')
    op.drop_column('drugs', 'property_taste')
    op.drop_column('drugs', 'category_name')
    op.drop_column('drugs', 'category_id')
    op.drop_column('ai_diagnosis_results', 'health_advice')
    op.drop_index(op.f('ix_schedules_id'), table_name='schedules')
    op.drop_index(op.f('ix_schedules_doctor_name'), table_name='schedules')
    op.drop_index(op.f('ix_schedules_date'), table_name='schedules')
    op.drop_table('schedules')
    op.drop_index(op.f('ix_nursing_records_patient_id'), table_name='nursing_records')
    op.drop_index(op.f('ix_nursing_records_id'), table_name='nursing_records')
    op.drop_table('nursing_records')
    op.drop_index(op.f('ix_followups_session_id'), table_name='followups')
    op.drop_index(op.f('ix_followups_patient_id'), table_name='followups')
    op.drop_index(op.f('ix_followups_id'), table_name='followups')
    op.drop_table('followups')
    op.drop_index(op.f('ix_drug_prices_name'), table_name='drug_prices')
    op.drop_index(op.f('ix_drug_prices_id'), table_name='drug_prices')
    op.drop_table('drug_prices')
    op.drop_index(op.f('ix_appointments_id'), table_name='appointments')
    op.drop_table('appointments')
    # ### end Alembic commands ###
